name: 'Remove labels'
description: 'Remove pull requests labels'
branding:
  icon: 'edit'
  color: 'yellow'
inputs:
  token:
    description: 'Github token'
    required: true
  labels:
    description: 'Labels to remove'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
